# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Legit
tagline:             'Yep.'
description:         'Legit X'
url:                 https://legit.github.io
baseurl:             'https://legit.github.io'
paginate:            5

# About/contact
author:
  name:              
  url:               
  email:             

# Custom vars
version:             2.0.0
