permalink:           :title
title:               Slasm
tagline:             ''
description:         ''
url:                 http://slasm.com
baseurl:             'http://slasm.com'
paginate:            1
