# Permalinks
#
permalink:           pretty

# Setup
title:               This guy right here
tagline:             'writes right here.'
description:         'This guy right here writes right here. About what you may ask. You''d fail in your task if you asked. He writes about what he damn well wants, now go eat some croissants.'
url:                 http://thisguyrighthere.com
baseurl:             'http://thisguyrighthere.com'
paginate:            1

# About/contact
author:
  name:              
  url:               
  email:             

# Custom vars
version:             2.0.0
