permalink:           :title
title:               Slasm
tagline:             ''
description:         ''
paginate:            1

# About/contact
author:
  name:              
  url:               
  email:             

# Custom vars
version:             2.0.0
