# Permalinks
#
permalink:           pretty

# Setup
title:               This Guy Right Here
tagline:             ''
description:         ''
url:                 http://thisguyrighthere.com
baseurl:             'http://thisguyrighthere.com'
paginate:            5

# About/contact
author:
  name:              
  url:               
  email:             

# Custom vars
version:             2.0.0
