# Permalinks
#
permalink:           pretty

# Setup
title:               slasm.com
tagline:             ''
description:         ''
url:                 http://slasm.com
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              
  url:               
  email:             

# Custom vars
version:             2.0.0
