# Permalinks
#
permalink:           pretty

# Setup
title:               This guy right here
tagline:             'writes right here.'
description:         'Greetings and salutations. This guy right here writes right here.'
url:                 http://thisguyrighthere.com
baseurl:             'http://thisguyrighthere.com'
paginate:            5

# About/contact
author:
  name:              
  url:               
  email:             

# Custom vars
version:             2.0.0
