permalink:           :year/:month/:day/:title/
title:               Slasm
copyright_name: Slasm
author: Slasm
tagline:             ''
description:         ''
url:                 'http://slasm.com'
paginate:            1
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-redirect-from
